/*
 * AntiIdleDialog.java
 *
 * Created on 2008年8月31日, 下午4:49
 */

package snailftp.view;

import java.awt.Component;
import javax.swing.*;
import snailftp.config.Config;
/**
 *
 * @author  jiangjizhong
 */
public class AntiIdleDialog extends javax.swing.JDialog {

    public static final int CANCEL_VALUE = 0;
    public static final int OK_VALUE = 1;
    private Config config = Config.getInstance();
    private int value = 0;
    boolean antiIdleEnable = false;
    int waitSecond = 5;
    String commandString = "NOOP";
    
    int getValue(){
        return this.value;
    }
    int getWaitSeoond(){
        return this.waitSecond;
    }
    
    String getCommandString(){
        return this.commandString;
    }
    /** Creates new form AntiIdleDialog */
    public AntiIdleDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        this.checkEnable();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        enableAntiIdle = new javax.swing.JCheckBox();
        inforPanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        waitSecondTextField = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        commandStringComboBox = new javax.swing.JComboBox();
        OK = new javax.swing.JButton();
        Cancel = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);

        enableAntiIdle.setText("启用反空闲");
        boolean selected = config.getBoolean(Config.ANTIIDLE_ENABLE_KEY);
        enableAntiIdle.setSelected(selected);
        enableAntiIdle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkEnable(evt);
            }
        });

        inforPanel.setBorder(javax.swing.BorderFactory.createTitledBorder("反空闲"));

        jLabel1.setText("等待时间：");

        waitSecondTextField.setText(config.getString(Config.ANTIIDLE_WAIT_KEY, "5"));

        jLabel2.setText("秒");

        jLabel3.setText("命令：");

        commandStringComboBox.setEditable(true);
        commandStringComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "NOOP", "PWD" }));
        if(config.getString(Config.ANTIIDLE_COMMAND_KEY) != null){
            commandStringComboBox.getEditor().setItem(config.getString(Config.ANTIIDLE_COMMAND_KEY));
        }

        javax.swing.GroupLayout inforPanelLayout = new javax.swing.GroupLayout(inforPanel);
        inforPanel.setLayout(inforPanelLayout);
        inforPanelLayout.setHorizontalGroup(
            inforPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(inforPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(inforPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(inforPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(inforPanelLayout.createSequentialGroup()
                        .addComponent(waitSecondTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel2))
                    .addComponent(commandStringComboBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        inforPanelLayout.setVerticalGroup(
            inforPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(inforPanelLayout.createSequentialGroup()
                .addGroup(inforPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(waitSecondTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(inforPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(commandStringComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        OK.setText("确定");
        OK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OKActionPerformed(evt);
            }
        });

        Cancel.setText("取消");
        Cancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CancelActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(inforPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(enableAntiIdle)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(OK)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(Cancel)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(enableAntiIdle)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(inforPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Cancel)
                    .addComponent(OK)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

private void checkEnable(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkEnable
    this.checkEnable();
}//GEN-LAST:event_checkEnable

private void error(Object message){
    JOptionPane.showMessageDialog(this, message, "错误", JOptionPane.ERROR_MESSAGE);
}
private void OKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OKActionPerformed
    
    if(this.antiIdleEnable){
        if(waitSecondTextField.getText().isEmpty()){
            error("请输入等待时间");
            return;
        }
        try{
            this.waitSecond = Integer.parseInt(this.waitSecondTextField.getText());
        }catch(NumberFormatException nfe){
            error("等待时间是一个整数");
            return;
        }
        if(this.waitSecond <= 0){
            error("等待时间必须大于0");
            return;
        }
        this.commandString = (String)this.commandStringComboBox.getEditor().getItem();
        if(this.commandString.isEmpty()){
            error("请输入要发送的命令");
            return;
        }
    }
    this.value = OK_VALUE;
    config.set(Config.ANTIIDLE_ENABLE_KEY, this.antiIdleEnable);
    config.set(Config.ANTIIDLE_WAIT_KEY, this.waitSecond);
    config.set(Config.ANTIIDLE_COMMAND_KEY, this.commandString);
    config.save();
    this.dispose();
}//GEN-LAST:event_OKActionPerformed

private void CancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CancelActionPerformed
    this.value = CANCEL_VALUE;
    this.dispose();
}//GEN-LAST:event_CancelActionPerformed

    void checkEnable(){
        this.antiIdleEnable = enableAntiIdle.isSelected() ? true : false;
        for(Component c : inforPanel.getComponents()){
            c.setEnabled(antiIdleEnable);
        }
        inforPanel.setEnabled(antiIdleEnable);
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Cancel;
    private javax.swing.JButton OK;
    private javax.swing.JComboBox commandStringComboBox;
    private javax.swing.JCheckBox enableAntiIdle;
    private javax.swing.JPanel inforPanel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JTextField waitSecondTextField;
    // End of variables declaration//GEN-END:variables

}
