/*
 * SiteDialog.java
 *
 * Created on 2008年8月29日, 下午9:01
 */
package snailftp.view;

import javax.swing.*;
import snailftp.site.*;
import java.util.*;
import java.io.File;

/**
 *
 * @author  jiangjizhong
 */
public class SiteDialog extends javax.swing.JDialog {

    public static final int NOTHING_OPERATION = 0;
    public static final int CONNECT_OPERATION = 1;
    private int value = SiteDialog.NOTHING_OPERATION;
    SiteManager siteManager = SiteManager.getInstance();
    private Site site = null;

    /** Creates new form SiteDialog */
    public SiteDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        init();
    }

    private void init() {
        this.listSite();
        if (siteList.getModel().getSize() > 0) {
            siteList.setSelectedIndex(0);
            String name = (String) siteList.getSelectedValue();
            site = siteManager.get(name);
            this.showSite();
            connect.setEnabled(true);
        }
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.JLabel jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        siteList = new javax.swing.JList();
        javax.swing.JLabel jLabel2 = new javax.swing.JLabel();
        javax.swing.JLabel jLabel3 = new javax.swing.JLabel();
        javax.swing.JLabel jLabel4 = new javax.swing.JLabel();
        host = new javax.swing.JTextField();
        port = new javax.swing.JTextField();
        javax.swing.JLabel jLabel5 = new javax.swing.JLabel();
        username = new javax.swing.JTextField();
        javax.swing.JLabel jLabel6 = new javax.swing.JLabel();
        password = new javax.swing.JPasswordField();
        javax.swing.JLabel jLabel7 = new javax.swing.JLabel();
        localDirectory = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        javax.swing.JLabel jLabel8 = new javax.swing.JLabel();
        remoteDirectory = new javax.swing.JTextField();
        addSite = new javax.swing.JButton();
        removeSite = new javax.swing.JButton();
        saveSite = new javax.swing.JButton();
        connect = new javax.swing.JButton();
        close = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        userPassiveModeCheckbox = new javax.swing.JCheckBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("站点管理器");
        setResizable(false);

        jLabel1.setText("站点列表");

        siteList.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                siteListValueChangedHandle(evt);
            }
        });
        jScrollPane1.setViewportView(siteList);

        jLabel2.setText("站点信息");

        jLabel3.setText("主机");

        jLabel4.setText("端口");

        port.setText("21");

        jLabel5.setText("用户名");

        jLabel6.setText("密码");

        jLabel7.setText("本地路径");

        jButton1.setText("选择");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel8.setText("远程路径");

        addSite.setText("添加站点");
        addSite.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addSiteActionPerformed(evt);
            }
        });

        removeSite.setText("删除站点");
        removeSite.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                removeSiteActionPerformed(evt);
            }
        });

        saveSite.setText("保存修改");
        saveSite.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveSiteActionPerformed(evt);
            }
        });

        connect.setText("连接");
        connect.setEnabled(false);
        connect.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                connectActionPerformed(evt);
            }
        });

        close.setText("关闭");
        close.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                closeActionPerformed(evt);
            }
        });

        jLabel9.setText("留空匿名");

        jLabel10.setText("以\"/\"开头");

        userPassiveModeCheckbox.setText("使用被动模式");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8)
                            .addComponent(jLabel7)
                            .addComponent(jLabel6)
                            .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, 79, Short.MAX_VALUE)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(host, javax.swing.GroupLayout.DEFAULT_SIZE, 175, Short.MAX_VALUE)
                                    .addComponent(username, javax.swing.GroupLayout.DEFAULT_SIZE, 175, Short.MAX_VALUE)
                                    .addComponent(localDirectory, javax.swing.GroupLayout.DEFAULT_SIZE, 175, Short.MAX_VALUE)
                                    .addComponent(remoteDirectory, javax.swing.GroupLayout.DEFAULT_SIZE, 175, Short.MAX_VALUE)
                                    .addComponent(password, javax.swing.GroupLayout.DEFAULT_SIZE, 175, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel4)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(port, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jLabel10)
                                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addComponent(userPassiveModeCheckbox)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(addSite)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(removeSite)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(saveSite)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 66, Short.MAX_VALUE)
                        .addComponent(connect)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(close)))
                .addContainerGap())
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {addSite, close, connect, removeSite, saveSite});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(port, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(host, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(username, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5)
                            .addComponent(jLabel9))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(password, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(localDirectory, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7)
                            .addComponent(jButton1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(remoteDirectory, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8)
                            .addComponent(jLabel10))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(userPassiveModeCheckbox))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addSite)
                    .addComponent(removeSite)
                    .addComponent(close)
                    .addComponent(saveSite)
                    .addComponent(connect))
                .addContainerGap(14, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

private void siteListValueChangedHandle(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_siteListValueChangedHandle
    String item = (String) siteList.getSelectedValue();
    if (item != null) {
        this.site = this.siteManager.get(item);
        this.showSite();
        connect.setEnabled(true);
    } else {
        connect.setEnabled(false);
    }
}//GEN-LAST:event_siteListValueChangedHandle

    private void error(Object message) {
        JOptionPane.showMessageDialog(this, message, "错误", JOptionPane.ERROR_MESSAGE);
    }

    private void saveSite() {
        try {
            this.siteManager.save();
        } catch (java.io.IOException exc) {
            error("无法保存站点信息：" + exc.getMessage());
        }
    }

private void addSiteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addSiteActionPerformed
    String name = JOptionPane.showInputDialog(this, "输入站点名称", "新建站点", JOptionPane.PLAIN_MESSAGE);//GEN-LAST:event_addSiteActionPerformed
        if (name != null) {
            Site s = new Site();
            s.setName(name);
            if (siteManager.add(s)) {
                this.saveSite();
                this.listSite();
                siteList.setSelectedValue(name, true);
            } else {
                error("名称为\"" + name + "\"已经存在！");
            }
        }
    }

private void removeSiteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_removeSiteActionPerformed
    Object[] names = siteList.getSelectedValues();
    for (Object obj : names) {
        String name = (String) obj;
        error("删除" + name);
        siteManager.remove(name);
    }
    this.saveSite();
    this.listSite();
}//GEN-LAST:event_removeSiteActionPerformed

private void saveSiteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveSiteActionPerformed
    if (this.site == null) {
        return;
    }
    try {
        this.site.setPort(Integer.parseInt(this.port.getText()));
    } catch (NumberFormatException nfe) {
        error("端口号必须是1-65535之间的整数");
    }
    this.site.setUsername(this.username.getText());
    this.site.setPassword(new String(this.password.getPassword()));
    this.site.setHost(this.host.getText().trim());
    this.site.setLocalDirectory(this.localDirectory.getText().trim());
    this.site.setRemoteDirectory(this.remoteDirectory.getText().trim());
    this.site.setUsePassiveMode(this.userPassiveModeCheckbox.isSelected());
    siteManager.update(site);
    this.saveSite();
}//GEN-LAST:event_saveSiteActionPerformed

private void connectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_connectActionPerformed
    this.value = CONNECT_OPERATION;
    this.saveSiteActionPerformed(evt);
    this.dispose();
}//GEN-LAST:event_connectActionPerformed

private void closeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_closeActionPerformed
    value = SiteDialog.NOTHING_OPERATION;
    this.dispose();
}//GEN-LAST:event_closeActionPerformed

private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
    JFileChooser fileChooser = new JFileChooser();
    fileChooser.setMultiSelectionEnabled(false);
    fileChooser.setFileSelectionMode(JFileChooser.DIRECTORIES_ONLY);
    int result = fileChooser.showOpenDialog(this);
    if (result == JFileChooser.CANCEL_OPTION) {
        return;
    }
    File localDir = fileChooser.getSelectedFile();
    localDirectory.setText(localDir.getAbsolutePath());
}//GEN-LAST:event_jButton1ActionPerformed

    public int getValue(){
        return this.value;
    }

    public Site getSite(){
        return this.site;
    }
    private void listSite(){
        Collection<Site> sites = siteManager.sites();
        List<String> list = new ArrayList<String>();
        for(Site s : sites){
            list.add(s.getName());
        }
        Collections.sort(list);
        DefaultListModel listModel = new DefaultListModel();
        for(String name : list){
            listModel.addElement(name);
        }
        siteList.setModel(listModel);
    }

    private void showSite(){
        if(this.site == null){
            site = new Site();
            site.setPort(21);
            site.setRemoteDirectory("/");
        }
        this.username.setText(site.getUsername());
        this.password.setText(site.getPassword());
        this.host.setText(site.getHost());
        this.port.setText(site.getPort() + "");
        this.localDirectory.setText(site.getLocalDirectory());
        this.remoteDirectory.setText(site.getRemoteDirectory());
        this.userPassiveModeCheckbox.setSelected(site.isUsePassiveMode());
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addSite;
    private javax.swing.JButton close;
    private javax.swing.JButton connect;
    private javax.swing.JTextField host;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField localDirectory;
    private javax.swing.JPasswordField password;
    private javax.swing.JTextField port;
    private javax.swing.JTextField remoteDirectory;
    private javax.swing.JButton removeSite;
    private javax.swing.JButton saveSite;
    private javax.swing.JList siteList;
    private javax.swing.JCheckBox userPassiveModeCheckbox;
    private javax.swing.JTextField username;
    // End of variables declaration//GEN-END:variables

}
